name: build_and_release

on:
  push:
    tags:
      - "*"
    branches:
        main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            platform: [ linux-armv7, linux-arm64 ]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@main
        with:
          path: './filebrowser.koplugin'
      - name: Download Filebrowser server binary
        id: get_filebrowser
        uses: robinraju/release-downloader@v1
        with:
          repository: 'filebrowser/filebrowser'
          latest: true
          preRelease: false
          fileName: '${{  matrix.platform  }}-filebrowser.tar.gz'
          out-file-path: 'filebrowser.koplugin/filebrowser'
          extract: true
      - name: Template our release name
        id: release_name
        run: |
          FILEBROWSER_TAG="${{steps.get_filebrowser.outputs.tag_name}}"
          if [[ "${{ github.ref_type  }}" == "tag" ]] ; then
            VERSION="${{  github.ref_name  }}-${FILEBROWSER_TAG#v}"
            # example: filebrowser.koplugin_v1.0-2.30.0-arm64.tar.gz
          else
            VERSION="${{  github.ref_name  }}_$(date -I)-${FILEBROWSER_TAG#v}"
            # example: filebrowser.koplugin_main_2024-07-15_2.30.0-arm64.tar.gz
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "outfile=filebrowser.koplugin_-${{  matrix.platform  }}.tar.gz" >> "$GITHUB_OUTPUT"
      - name: Compress archive
        run: tar -czvf "${{  steps.release_name.outputs.outfile  }}" filebrowser.koplugin
      - uses: actions/upload-artifact@v4
        with:
          name: ${{  steps.release_name.outputs.outfile  }}
          path: ${{  steps.release_name.outputs.outfile  }}
      - name: upload release
        id: upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd filebrowser.koplugin
            gh release delete ${{  steps.release_name.outputs.version  }} --yes || true
            gh release create ${{  steps.release_name.outputs.version  }} --latest --generate-notes ../${{  steps.release_name.outputs.outfile  }}