name: build_and_release

on:
  push:
    tags:
      - "*"
    branches:
        main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            arch: [ linux-armv7, linux-arm64 ]
    steps:
      - name: Checkout this repository
        uses: actions/checkout@main
        with:
          path: './filebrowser.koplugin'
      - name: Download Filebrowser server binary
        id: get_filebrowser
        uses: robinraju/release-downloader@v1
        with:
          repository: 'filebrowser/filebrowser'
          latest: true
          preRelease: false
          fileName: '${{matrix.arch}}-filebrowser.tar.gz'
          out-file-path: 'filebrowser.koplugin/filebrowser'
          extract: true
      - name: Template our release name
        id: release_name
        run: |
          FILEBROWSER_TAG="${{steps.get_filebrowser.outputs.tag_name}}"
          echo "OUTFILE=filebrowser.koplugin_${{  github.ref_name  }}-${FILEBROWSER_TAG#v}.tar.gz" | tee -a "$GITHUB_OUTPUT"
          # examples: filebrowser.koplugin_v1.0-2.30.0.tar.gz, filebrowser.koplugin_main-2.30.0.tar.gz
      - name: Compress archive
        run: tar -czvf "${{  steps.get_filebrowser.outputs.OUTFILE  }}" filebrowser.koplugin
      - uses: actions/upload-artifact@v4
        with:
          name: ${{  steps.get_filebrowser.outputs.outfile  }}
          path: ${{  steps.get_filebrowser.outputs.outfile  }}
      - name: upload release
        id: upload
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd filebrowser.koplugin
            gh release delete ${{  steps.get_filebrowser.outputs.outfile  }} --yes || true
            gh release create ${{  steps.get_filebrowser.outputs.outfile  }} --latest --generate-notes ../${{  steps.get_filebrowser.outputs.outfile  }}